"""
WeatherGPT - Member 3
Advisory Schemas

Defines standardized decision-support structures for
agriculture, aviation, marine, urban, and disaster-management
weather advisories.
"""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field, ConfigDict

from schemas.risk import RiskLevel


class AdvisoryDomain(str, Enum):
    """
    Domain for which a weather advisory is generated.
    """

    GENERAL = "GENERAL"
    AGRICULTURE = "AGRICULTURE"
    AVIATION = "AVIATION"
    MARINE = "MARINE"
    URBAN = "URBAN"
    DISASTER_MANAGEMENT = "DISASTER_MANAGEMENT"


class AdvisoryPriority(str, Enum):
    """
    Priority level indicating how urgently an advisory
    should be acted upon.
    """

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AdvisoryResult(BaseModel):
    """
    Represents a structured decision-support advisory
    generated by the Member 3 Advisory Engine.
    """

    model_config = ConfigDict(
        validate_assignment=True
    )

    domain: AdvisoryDomain = Field(
        ...,
        description="Domain for which the advisory is intended."
    )

    priority: AdvisoryPriority = Field(
        ...,
        description="Urgency level of the advisory."
    )

    risk_level: RiskLevel = Field(
        ...,
        description="Weather risk level associated with the advisory."
    )

    title: str = Field(
        ...,
        min_length=1,
        description="Short title of the advisory."
    )

    message: str = Field(
        ...,
        min_length=1,
        description="Main advisory message."
    )

    actions: list[str] = Field(
        default_factory=list,
        description="Recommended actions for the user or organization."
    )

    location_name: str = Field(
        ...,
        min_length=1,
        description="Location associated with the advisory."
    )

    issued_at: datetime = Field(
        ...,
        description="Time when the advisory was generated."
    )

    valid_until: datetime | None = Field(
        default=None,
        description="Time until which the advisory remains relevant."
    )

    source: str | None = Field(
        default=None,
        description="Source of the weather information used for the advisory."
    )