"""
WeatherGPT - Member 3
Alert Schemas

Defines standardized structures for weather alerts and warnings
generated by the Member 3 Intelligence and Decision-Support Engine.
"""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field, ConfigDict

from schemas.hazard import HazardType
from schemas.risk import RiskLevel


class AlertStatus(str, Enum):
    """
    Lifecycle state of a weather alert.
    """

    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class AlertResult(BaseModel):
    """
    Represents a structured weather alert generated by
    the Member 3 Alert Engine.
    """

    model_config = ConfigDict(
        validate_assignment=True
    )

    alert_type: HazardType = Field(
        ...,
        description="Type of hazard for which the alert is issued."
    )

    severity: RiskLevel = Field(
        ...,
        description="Severity level of the alert."
    )

    status: AlertStatus = Field(
        default=AlertStatus.ACTIVE,
        description="Current lifecycle status of the alert."
    )

    title: str = Field(
        ...,
        min_length=1,
        description="Short title of the alert."
    )

    description: str = Field(
        ...,
        min_length=1,
        description="Structured description of the weather threat."
    )

    location_name: str = Field(
        ...,
        min_length=1,
        description="Location affected by the alert."
    )

    issued_at: datetime = Field(
        ...,
        description="Time when the alert was issued."
    )

    valid_from: datetime = Field(
        ...,
        description="Time from which the alert becomes valid."
    )

    valid_until: datetime = Field(
        ...,
        description="Time until which the alert remains valid."
    )

    recommended_action: str = Field(
        ...,
        min_length=1,
        description="Recommended safety or preparedness action."
    )

    source: str | None = Field(
        default=None,
        description="Source responsible for the underlying weather information."
    )