"""
WeatherGPT - Member 3
Unified Weather Intelligence Schema

Defines the standardized output produced by the Weather
Intelligence and Decision-Support Engine.

This model acts as the integration contract between Member 3
and downstream components such as the LLM engine, mobile
application, voice layer, and notification systems.
"""

from datetime import datetime

from pydantic import BaseModel, Field, ConfigDict

from schemas.advisory import AdvisoryResult
from schemas.alert import AlertResult
from schemas.climate import ClimateAnalysis
from schemas.hazard import HazardResult
from schemas.risk import RiskAssessment


class WeatherIntelligenceResult(BaseModel):
    """
    Unified result generated by the Member 3 intelligence layer.

    It combines risk assessment, detected hazards, alerts,
    domain-specific advisories, and climate analysis into one
    machine-readable response.
    """

    model_config = ConfigDict(
        validate_assignment=True
    )

    location_name: str = Field(
        ...,
        min_length=1,
        description="Primary location associated with the intelligence result."
    )

    generated_at: datetime = Field(
        ...,
        description="Timestamp when the intelligence result was generated."
    )

    risk_assessment: RiskAssessment | None = Field(
        default=None,
        description="Overall and component-level weather risk assessment."
    )

    hazards: list[HazardResult] = Field(
        default_factory=list,
        description="Weather hazards detected for the location."
    )

    alerts: list[AlertResult] = Field(
        default_factory=list,
        description="Active or relevant weather alerts."
    )

    advisories: list[AdvisoryResult] = Field(
        default_factory=list,
        description="Domain-specific decision-support advisories."
    )

    climate_analysis: list[ClimateAnalysis] = Field(
        default_factory=list,
        description="Historical climate trends and anomaly analysis."
    )

    processing_version: str = Field(
        default="1.0.0",
        min_length=1,
        description="Version of the Member 3 intelligence processing pipeline."
    )